services:
  postgres:
    image: postgres:latest
    container_name: practices
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: studentpractices
      POSTGRES_DB: practices_db
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - "5332:5432"
    networks:
      - db

volumes:
  db:

networks:
  db: